# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5961e88e2aea36a1010ad7991ff863ee0dfad790daeaddaa6d78d2be3e6de29a4422cc1a777a8de0b23a3cca4fe0d8a090ac67cdc88e71265876f8ff9745a2b1

test:
  secret_key_base: 1b76a0f277a5275056fc2b081e167416e6e83e4ab0f23547ece06b97c40b0f23995caaba1fe9e7cac1952b6251dd467a693458e46a24c90a8d96628a7d1d8d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
